/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

public class App {
    public String getGreeting() {
        return "Hello world. checking build ok";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
		System.out.println("Build ok if you see this line");
    }
}
